# Generated by Django 5.0.1 on 2024-01-29 12:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync', models.BooleanField(default=True)),
                ('encrypted_password', models.TextField()),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passManager.domain')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('deprecated', 'Deprecated'), ('created', 'Created'), ('deleted', 'Deleted'), ('updated', 'Updated')], max_length=10)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passManager.passwordvault')),
            ],
        ),
        migrations.AddField(
            model_name='domain',
            name='vault',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passManager.passwordvault'),
        ),
        migrations.AlterUniqueTogether(
            name='domain',
            unique_together={('vault', 'name')},
        ),
    ]
